YoloTomatoTrained-master/eyic-project/core/urls.py
from django.urls import path
from django.urls import path
from .views import *


app_name = "core"

urlpatterns = [
    path("farm-video-upload/", farm_video_upload, name="farm_video_upload"),
    path("your-results/", your_results, name="your_results"),
    path("results/<int:request_id>/", results, name="results"),
    path("", index, name="index"),
]

YoloTomatoTrained-master/eyic-project/eyic_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YoloTomatoTrained-master/eyic-project/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
video_render_status = (
    ("completed", "completed"),
    ("processing", "processing"),
)



class Crop(models.Model):
    name=models.CharField(max_length=30)
    
    ph_farm_less=models.PositiveBigIntegerField()
    ph_farm_more=models.PositiveBigIntegerField()

    moisture_farm_less=models.PositiveBigIntegerField()
    moisture_farm_more=models.PositiveBigIntegerField()

    temperature_farm_less=models.PositiveBigIntegerField()
    temperature_farm_more=models.PositiveBigIntegerField()

    total_amt_salt_farm_less=models.PositiveBigIntegerField()
    total_amt_salt_farm_more=models.PositiveBigIntegerField()


    def __str__(self):
        return self.name

class FarmVideo(models.Model):
    user = models.ForeignKey(User, related_name="farm_videos", on_delete=models.CASCADE)
    video = models.FileField(
        upload_to="videos_uploaded",
        validators=[
            FileExtensionValidator(
                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
            )
        ],
    )
    ph_farm=models.FloatField()
    moisture_farm=models.FloatField()
    temperature=models.PositiveBigIntegerField()
    total_amt_salt=models.PositiveBigIntegerField()

    
    status = models.CharField(
        verbose_name="Status",
        default="processing",
        choices=video_render_status,
        max_length=10,
    )    
    created = models.DateTimeField(verbose_name="Created", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Updated", auto_now=True)

    class Meta:
        verbose_name = "FarmVideo"
        verbose_name_plural = "FarmVideos"



class VideoFarmImages(models.Model):
    farm_video = models.ForeignKey(
        FarmVideo, related_name="video_farm_images", on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="video_farm_images")


    created = models.DateTimeField(verbose_name="Created", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Updated", auto_now=True)

    class Meta:
        verbose_name = "VideoFarmImages"
        verbose_name_plural = "VideoFarmImagess"




class Disease(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to="disease_images",null=True)

    def __str__(self):
        return self.name


class DetactFarmImages(models.Model):
    farm_images = models.ForeignKey(
        VideoFarmImages, related_name="detact_farm_images", on_delete=models.CASCADE
    )
    disease_detected = models.ManyToManyField(
        Disease, related_name="frame_disease", blank=True
    )

    created = models.DateTimeField(verbose_name="Created", auto_now_add=True)
    updated = models.DateTimeField(verbose_name="Updated", auto_now=True)

    class Meta:
        verbose_name = "DetactFarmImages"
        verbose_name_plural = "DetactFarmImagess"

YoloTomatoTrained-master/eyic-project/core/forms.py
from django import forms
from core.models import *



class FarmVideoUploadForm(forms.ModelForm):
    class Meta:
        model = FarmVideo
        fields = ("video","ph_farm","moisture_farm","temperature","total_amt_salt")

YoloTomatoTrained-master/eyic-project/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import FarmVideoUploadForm
from core.models import *
from django.http import JsonResponse

from .utils import convert_video_images, save_frame


@login_required
def farm_video_upload(request):
    if request.method == "POST":
        form = FarmVideoUploadForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            form_obj = form.save(commit=False)
            form_obj.user = request.user
            form.save()
            convert_video_images(form_obj.id)
            return render(request, "users/farm_video_upload.html", {"form": form})

        else:
            return render(request, "users/farm_video_upload.html", {"form": form})

    form = FarmVideoUploadForm()
    return render(request, "users/farm_video_upload.html", {"form": form})

def divide_list(lst):
    # Calculate the length of each sublist
    sublist_length = len(lst) // 10
    
    # Create a list of empty sublists
    sublists = [[] for _ in range(10)]
    
    # Fill each sublist with its corresponding elements from the original list
    for i, item in enumerate(lst):
        sublist_index = i // sublist_length
        sublists[sublist_index].append(item)
    
    return sublists


# create a / for index.html
def index(request):
    return render(request, "index.html")


@login_required
def results(request, request_id):
    farm_video_obj = FarmVideo.objects.get(id=request_id)
    all_frame_images = farm_video_obj.video_farm_images.all()
    l = []
    for i in all_frame_images:
        detact_obj = i.detact_farm_images.all()[0]

        if detact_obj.disease_detected.all() != []:
            for j in detact_obj.disease_detected.all():
                l.append(j)
            # print(detact_obj.disease_detected.all(),i)
    # print(divide_list(l))        
    # print(l,len(l))
    disease_counts = {}
    for disease in l:
        if disease.name in disease_counts:
            disease_counts[disease.name] += 1
        else:
            disease_counts[disease.name] = 1
    key_of_dict = []
    val_of_dict = []

    for i in disease_counts:
        key_of_dict.append(i)
        val_of_dict.append(disease_counts[i])


    total_percentage=sum(val_of_dict)
    good_crops_percetage=round((disease_counts.get("Healthy",0)/total_percentage)*100,2)
    bad_crops_percetage=round(100-good_crops_percetage,2)
    model_disease_dict=[]
    for disease_name in key_of_dict:
        if disease_name!="Healthy":
            disease_obj=Disease.objects.get(name=disease_name)
            model_disease_dict.append(disease_obj)
    context = {
        "key_of_dict": key_of_dict,
        "val_of_dict": val_of_dict,
        "good_crops_percetage": good_crops_percetage,
        "bad_crops_percetage": bad_crops_percetage,
        "model_disease_dict": model_disease_dict,
        "farmer_video":farm_video_obj,
        "disease_counts": disease_counts,
    }



    return render(request, "results.html", context)


@login_required
def your_results(request):
    farmer_video = FarmVideo.objects.filter(user=request.user).order_by("-created")
    # print(farmer_video)

    return render(request, "report_table.html", {"farmer_video": farmer_video})

YoloTomatoTrained-master/eyic-project/templates/base.html
{% load static %}
{% load i18n %}




<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>{% block title %}{% endblock %}| Prutuvainya</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
  <!-- MDB -->
     <link rel="shortcut icon" type="image/png" href="{% static 'logo_images/favicon1.png' %}"/>
  <link rel="stylesheet" href="{% static "css/mdb.min.css" %}" />
  <!-- Custom styles -->
  <link rel="stylesheet" href="{% static "css/admin.css" %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
    crossorigin="anonymous"></script>
    <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
</head>


<body>






  

    {% include "navi.html" %}

        {% if messages %}
      
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}

           
          </div>
        


          {% endfor %}
          
          
    {% endif %}



            {% block content_main  %}
        {% endblock content_main %} 


        {% block content1  %}
        {% endblock content1 %}
        <div class="container ">
        {% block content  %}
        {% endblock content %} 
    </div>


<!-- Footer -->
<footer class=" text-center text-white" style="background-color:#083513;">
  <!-- Grid container -->
  <div class="container p-4">



    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example2" class="form-control" />
              <label class="form-label" for="form5Example2">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">

            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->


    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Pruthuvainya empowers Indian agriculture by utilizing technology to address the challenges faced by
        farmers.
        Through our innovative classification model, we provide farmers with real-time reports that identify
        diseased plants, their percentage, specific diseases, and recommended remedies, enhancing crop
        management
        and productivity
      </p>
    </section>
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2023 Copyright:
    <a class="text-white" href="#">Prutuvainya.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->



  <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
  <!-- Custom scripts -->
  <script type="text/javascript" src="{% static "js/admin.js" %}"></script>
</body>

</html>

YoloTomatoTrained-master/eyic-project/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Main Page{% endblock %}

<style>

#overlay {
  position: fixed; /* Sit on top of the page content */
  display: none; /* Hidden by default */
  width: 100%; /* Full width (cover the whole page) */
  height: 100%; /* Full height (cover the whole page) */
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0,0,0,0.5); /* Black background with opacity */
  z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
  cursor: pointer; /* Add a pointer on hover */
}
</style>


{% block content1 %}

<div id="carouselBasicExample" class="carousel slide carousel-fade"  data-mdb-ride="carousel">
    <!-- Indicators -->


    <!-- Inner -->
    <div class="carousel-inner">
      <!-- Single item -->
      <div class="carousel-item active">

        
        <video autoplay loop muted class="video"  class="d-block w-100"  style="width: 100%;height: 700px;"  id="overlay">
            <source src='{% static  "video/video.mp4" %}' type="video/mp4" />
        </video>
        <div class="carousel-caption d-none d-md-block">
          <h1 style="font-size:400%">Welcome to Our Farm!</h1>
          <p>Pruthuvainya empowers Indian agriculture by utilizing technology to address the challenges faced by
            farmers.
            Through our innovative classification model, we provide farmers with real-time reports that identify
            diseased plants, their percentage, specific diseases, and recommended remedies, enhancing crop
            management
            and productivity</p>
        </div>
      </div>
  
    </div>
    <!-- Inner -->
  </div>
{% endblock content1 %}
{% block content %}

<hr>
<div class="card">
    <div class="card-body">
      <h1 class="card-title">Welcome to Our Farm</h1>
      <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
      <p class="card-text">
        Pruthuvainya empowers Indian agriculture by utilizing technology to address the challenges faced by
            farmers.
            Through our innovative classification model, we provide farmers with real-time reports that identify
            diseased plants, their percentage, specific diseases, and recommended remedies, enhancing crop
            management
            and productivity.
      </p>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card h-100">
        <img src="{% static 'images/drone.jpg' %}" class="card-img-top" alt="Skyscrapers"/>
        <div class="card-body">
          <h3 class="card-title">Krushi Karmi </h3>
        </div>
     <div class="card-footer text-center">
           <a href="#!" class="btn btn-success btn-lg btn-rounded text-bold" style="text-transform: capitalize;">Buy  <i class="fas  fa-indian-rupee-sign"></i>  45,000 </a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="{% static 'images/hardware.jpg' %}" style="height: 39vh;" class="card-img-top" alt="Los Angeles Skyscrapers"/>
        <div class="card-body">
          <h3 class="card-title">Krushi Bhumi Yanta</h3>
        </div>
     <div class="card-footer text-center">
           <a href="#!" class="btn btn-success btn-lg btn-rounded" style="text-transform: capitalize;">Buy  <i class="fas  fa-indian-rupee-sign"></i>  6,000 </a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/042.webp" class="card-img-top" alt="Palm Springs Road"/>
        <div class="card-body">
          <h3 class="card-title">Combo</h3>
        </div>
        <div class="card-footer text-center">
           <a href="#!" class="btn btn-success btn-lg btn-rounded" style="text-transform: capitalize;">Buy  <i class="fas  fa-indian-rupee-sign"></i> 53,000</a>
        </div>
      </div>
    </div>
  </div>




<br>





{% endblock content %}

YoloTomatoTrained-master/eyic-project/templates/main_home_page.html
{% extends 'base.html' %}
{% load static %}
{% block content1 %}
<div class="container pt-10" style="margin-top: 90px;">
<center>
  <img src="{% static 'logo_images/BannerLogo_crop.png' %}" width="200" height="150" class="d-inline-block align-top" alt="">
  <hr width="50%">
<h5 class="mb-3 h5 text-muted"> To use <b>Digital Listing Manager<b> Features, such as; Creating New Listings, Updating Existing Listings and Quantities. You need to authorize Easy Listing Upload to connect to your Etsy Shop.</h4>
  <a href="{% url 'account_logout' %}">
  <button type="button" class="btn btn-danger btn-lg">All in one Login</button>
  </a>
</center>
<hr class="my-4" />
<div class="row">
<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="Hollywood Sign on The Hill"/>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">
          This is a longer card with supporting text below as a natural lead-in to
          additional content1. This content is a little bit longer.
        </p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/042.webp" class="card-img-top" alt="Palm Springs Road"/>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">
          This is a longer card with supporting text below as a natural lead-in to
          additional content. This content is a little bit longer.
        </p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/043.webp" class="card-img-top" alt="Los Angeles Skyscrapers"/>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/044.webp" class="card-img-top" alt="Skyscrapers"/>
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">
          This is a longer card with supporting text below as a natural lead-in to
          additional content. This content is a little bit longer.
        </p>
      </div>
    </div>
  </div>
</div>
</div>
</div>
 {% endblock content1 %}

YoloTomatoTrained-master/eyic-project/templates/navi.html
<style>
          .navbar .nav-link {
        color: #fff !important;}
</style>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-success none d-lg-block" style="z-index: 2000;background-color: rgb(7, 41, 7);">
      <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand nav-link" href="/">
          <strong>Prutuvainya</strong>
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">


          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "core:farm_video_upload" %}" >Farm Video</a>
            </li>

               <li class="nav-item">
              <a class="nav-link" href="{% url "core:your_results" %}">My Results</a>
            </li>

            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "account_login" %}">Login </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "account_signup" %}">Register</a>
            </li>


          {% endif %}
          </ul>

          <ul class="navbar-nav d-flex flex-row">
             {% if user.is_authenticated %}

            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="https://www.youtube.com/@krushikarmi" rel="nofollow"
                target="_blank">
                <i class="fab fa-youtube"></i>
              </a>
            </li>


              <a
                class="dropdown-toggle d-flex align-items-center hidden-arrow"
                href="#"
                id="navbarDropdownMenuAvatar"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >


              
                <img
                  src="https://ui-avatars.com/api/?name={{user.username}}"
                  class="rounded-circle"
                  height="25"
                  alt="Black and White Portrait of a Man"
                  loading="lazy"
                />
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdownMenuAvatar"
              >
                <li>
                  <a class="dropdown-item" href="#">My profile</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Settings</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url "account_logout" %}">Logout</a>
                </li>
         {% endif %}
             
          
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->

YoloTomatoTrained-master/eyic-project/templates/pagination.html
<!--Pagination-->
<nav class="d-flex justify-content-center wow fadeIn">
  <ul class="pagination pg-blue">

    <!--Arrow left-->
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}

    {% for num in page.paginator.page_range %}
      {% if page.number == num %}
        <li class="page-item active">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
      {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
        <li class="page-item">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--Pagination-->

YoloTomatoTrained-master/eyic-project/templates/payments/payment_canceled.html
{% extends "base.html" %}

{% block content %}

    <p>Payment cancelled.</p>

{% endblock %}

YoloTomatoTrained-master/eyic-project/templates/payments/payment_done.html
{% extends "base.html" %}

{% block content %}

    <p>Payment done.</p>

{% endblock %}

YoloTomatoTrained-master/eyic-project/templates/report_table.html
{% extends "base.html" %}
{% load static %}
{% block title %}Report Table{% endblock %}
{% block content %}

    <br>
     <h3 class="display-4">Report Table</h3>
  <br>
  <hr>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Sr. No</th>
      <th scope="col">Video</th>
      <th scope="col">Status</th>
      <th scope="col">Created</th>
      <th scope="col">Link</th>
    </tr>
  </thead>
  <tbody>
  {% for video in farmer_video %}
    <tr>
      <th scope="row">{{forloop.counter }}</th>
      <td>{{video.video}}</td>
      <td>{{video.status}}</td>
      <td>{{video.created}}</td>
      <td>
  {% if video.status == "processing"  %}     
  <a href="#"    class="btn btn-sucess btn-sm active" role="button" aria-pressed="true">Please Wait for Result</a>

  {% else %}
  <a href="{% url "core:results" video.id  %}"    class="btn btn-primary btn-sm active" role="button" aria-pressed="true">View Result</a>
  

{% endif %}
     
      </td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock content %}

YoloTomatoTrained-master/eyic-project/templates/users/farm_video_upload.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Video Upload {% endblock %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<style>
    .not-visible{
        display: none;
    }
</style>

<!-- Vertically centered modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" id="exampleModalLabel"> <center> Video Uploaded</center></h5>
        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center"><i class="far fa-check-circle" style="font-size:500%;color:green"></i>
      <br />
      <hr>
      <h5>A video is being processed. check the status under the <b> Result </b> tab.</h5>
      </div>
      <div class="modal-footer">

        <a  href="{% url "core:your_results" %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">View Results</a>
      </div>
    </div>
  </div>
</div>
 <div class="container my-4">

</div>
      <section class="mb-4">
        <div class="card">
          <div class="card-header py-3">
            <h3 class="mb-0 text-center"><strong>Upload Farm Video</strong></h3>
          </div>



          <div class="card-body container text-center">

              <form action="" method="post" id="upload_form" enctype="multipart/form-data"> 
                  {% csrf_token %}
                  {{form|crispy}}
                  <br>
                  <input type="submit" value=" Upload Farm Video" class="btn btn-lg  btn-success" task>  
                  <br>
                  <br>
              </form>
               <div class="container not-visible progress" id="progress">
          </div>

          <br>
          <br>
      </section>

<script>
        {% comment %} const uploadForm = document.getElementById('upload_form'); {% endcomment %}
        const input_file = document.getElementById('id_video');
        const progress_bar = document.getElementById('progress');
        
        {% comment %} $("#upload_form").submit(function(e){
            e.preventDefault();
            $form = $(this)
            var formData = new FormData(this);
            const media_data = input_file.files[0];
            if(media_data != null){
                console.log(media_data);
                progress_bar.classList.remove("not-visible");
            }

            $.ajax({
                type: 'POST',
                url:'',
                data: formData,
                dataType: 'json',
                beforeSend: function(){

                },
                xhr:function(){
                    const xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener('progress', e=>{
                        if(e.lengthComputable){
                            const percentProgress = (e.loaded/e.total)*100;
                            console.log(percentProgress);
                            progress_bar.innerHTML = `<div class="progress-bar progress-bar-striped bg-success" 
                    role="progressbar" style="width: ${percentProgress}%" aria-valuenow="${percentProgress}" aria-valuemin="0" 
                    aria-valuemax="100"></div>`
                        }
                    });
                    return xhr
                },
                success: function(response){
                    // console.log("image_url",window.origin+response.image_url);
                    let image_url=window.origin+response.image_url;
                     navigator.clipboard.writeText(image_url);
                    uploadForm.reset()
                    progress_bar.classList.add('not-visible')
                },
                error: function(err){
                    console.log(err);
                },
                cache: false,
                contentType: false,
                processData: false,
            });
        }); {% endcomment %}

    </script>
{% endblock content %}